version: '2.0'

services:
  hyperion:
    build: .
    container_name: hyperionng
    volumes:
      - hyperionng-config:/config
    ports:
      - "19400:19400"
      - "19444:19444"
      - "19445:19445"
      - "8090:8090"
      - "8092:8092"
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 80:80

volumes:
  hyperionng-config: